### ISSUE TITLE
新功能请求

### ISSUE THREAD

**Issue by lveMonsi** [ZerephD/SimpfunManage#2]
请求支持环境变量方式配置 token 等参数，支持 vercel 环境变量配置，避免直接写在 github 仓库内造成 token 泄露
<img width="644" alt="image" src="https://github.com/ZerephD/SimpfunManage/assets/109103173/ea5c2255-5dca-4dc5-bb87-6ce852a64bb3">

**Comment by ZerephD** [comment]
初四生平时没空啊，周末有空搞🙁

**Comment by ZerephD** [comment]
加了，部署方法也在博客里更新了
